name: GalaranTools
main: me.galaran.bukkittools.GalaranTools
version: 2.2
author: Galaran

load: POSTWORLD

commands:
    gtools:
        description: Galarans tools main command
        permission: gtools.main
        permission-message: You do not have permission
        aliases: [gt]
    sayas:
        description: Say as command
        permission: gtools.sayas
        permission-message: You do not have permission
    playercmd:
        description: Execute player command from console
        permission: gtools.playercmd
        permission-message: You do not have permission
        aliases: [pcmd]

permissions:
    gtools.main:
        default: op
    gtools.sayas:
        default: op
    gtools.playercmd:
        default: op